### ISSUE TITLE
npm ERR! enoent ENOENT: no such file or directory

### ISSUE THREAD

**Issue by smejkka3** [smblott-github/chromix-too#14]
Hi,

I did successful installation over two weeks ago, but somehow I uninstalled the chromix-too and when I'm trying to install it again there is this error:
npm ERR! path /usr/lib/node_modules/chromix-too/server.js
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod
npm ERR! enoent ENOENT: no such file or directory, chmod '/usr/lib/node_modules/chromix-too/server.js'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/spotcap/.npm/_logs/2017-11-24T13_30_03_302Z-debug.log

I tried several ubuntu and on none of them it didn't work, got the same error.
Is there some solution to this?

Thanks

**Comment by smblott-github** [comment]
Thanks for the report.

This is npm silently ignoring files listed in `.gitignore` (which, to my mind, is silly).

Should be fixed now.

**Comment by smejkka3** [comment]
Thanks for quick fix!
