### ISSUE TITLE
Calling document function hangs on result

### ISSUE THREAD

**Issue by lufinkey** [smblott-github/chromix-too#15]
calling the command `chromix-too raw document.querySelector video` causes chromix-too to sit and do nothing indefinitely.

**Comment by smblott-github** [comment]
1. Only background-page operations are supported.  `document` is in the content page.
2. Chromix-too knows nothing about the specific APIs available.  It just adds a callback to the invocation and waits for the callback to be called.  Hence the behaviour that you're seeing.  The callback is never being called.

**Comment by lufinkey** [comment]
Alright I see. When I get the time, I'm probably going to fork this to allow loading of external javascript files into the current tab.
